### ISSUE TITLE
Should this project work?

### ISSUE THREAD

**Issue by ImAleeexx** [AfonsoFGarcia/hass-bluecon#1]
Hello, i tried setting up this project in HACS but after doing the login process the integration fails and shows this error
![image](https://github.com/AfonsoFGarcia/hass-bluecon/assets/52298617/806ef66e-e8d2-473f-8794-ac9192f1e33d)

**Comment by ImAleeexx** [comment]
When i click on configure at the 3 dot men shows this error
![image](https://github.com/AfonsoFGarcia/hass-bluecon/assets/52298617/279ed518-0031-4378-870b-7a506ab271d7)

**Comment by ImAleeexx** [comment]
I have edited the oauth credentials json file wich was empty with the correct data and i got 1 device with 3 sensors but i dont know if something more should show up in the device 
![image](https://github.com/AfonsoFGarcia/hass-bluecon/assets/52298617/94eb15bd-4a9e-400d-8488-5dc30192c9a4)

**Comment by ImAleeexx** [comment]
`{"access_token": "<accessToken>", "expires_on": "2023-12-05T17:41:48.656517"}`

**Comment by AfonsoFGarcia** [comment]
Hey! Sorry, didn't really have time to progress much further with this. I've only tested it with my setup (running on docker) and for me it works just fine. Can you let me know how you're running HA? Perhaps it's something related with permissions on the file editing that is causing the credentials.json file to not be created properly.

Regarding the entities, you're missing 2 entities: one lock and one camera. Can you provide the logs for the initialisation of the integration?

**Comment by ImAleeexx** [comment]
The files have the correct permissions, i cannot find where the logs are. Could you guide me to send them?

**Comment by viseniv** [comment]
I have the same problem.
How i can edit manually the credentials file?

**Comment by cvc90** [comment]
The oauth_token.json, credentials.json and persistent_ids.txt files do not seem to be created properly as they are created but empty.

Could you put a copy of these files as a sample so I can create them manually?

**Comment by viseniv** [comment]
I think this project is abandoned, for me it does not create any files.

**Comment by hugo1906** [comment]
> When i click on configure at the 3 dot menu shows this error ![image](https://private-user-images.githubusercontent.com/52298617/284084204-279ed518-0031-4378-870b-7a506ab271d7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQzMjYxMzEsIm5iZiI6MTcyNDMyNTgzMSwicGF0aCI6Ii81MjI5ODYxNy8yODQwODQyMDQtMjc5ZWQ1MTgtMDAzMS00Mzc4LTg3MGItN2E1MDZhYjI3MWQ3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODIyVDExMjM1MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJhN2FkYzc5OGY2NjE3MmFjNTY5ZjcyNmU5OTBlOWRlNzA5N2Y5MzJjZTgxNWIwYTllYmIzYThkYTBhYjNiOTEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.GTlE9-p7lGtTshV0UN3BVhzNLVfXSLWlk1tHBJnZiXs)

I have the same problem
runing HomeAssistant on a mini pc

**Comment by pchaves1** [comment]
Afonso,

pode dar aqui uma ajuda rápida?

**Comment by AfonsoFGarcia** [comment]
Hi all!

I am really sorry I haven't been able to help you guys. I would love to do it but with all that's going on with my work the last thing I want to do after leaving work is continue coding on something else. I can't really promise anything and I don't want to but I'll try to check it as there are some error logs on the latest versions of Haas related with blocking calls on the event loop.

Providing you with the files would not be useful as they cannot be created manually. If you're willing to execute the communication library locally on your machines, if you follow the quickstart on https://bluecon.afonsogarcia.dev/quickstart/ then you will be able to get both the credentials.json and persistent_ids.txt files that you can use in Haas.

As for the oauth_token.json you can use the example provided by @ImAleeexx as is, since the date is in the past it will request a new oauth token.

Let me know if all this helps.

**Comment by pchaves1** [comment]
Hello Afonso, 
thank you for your reply.

on the HA log we see this error:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 604, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/bluecon/__init__.py", line 26, in async_setup_entry
    bluecon = BlueConAPI.create_already_authed(notification_callback, ConfigFolderOAuthTokenStorage(hass, entry), ConfigFolderNotificationInfoStorage(hass, entry))
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/bluecon/BlueConAPI.py", line 53, in create_already_authed
    if oAuthTokenStorage.retrieveOAuthToken() is not None:
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/bluecon/ConfigFolderOAuthTokenStorage.py", line 17, in retrieveOAuthToken
    return OAuthToken.fromJson(f.read())
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/bluecon/oauth/OAuthToken.py", line 38, in fromJson
    return OAuthToken(loads(json))
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/bluecon/oauth/OAuthToken.py", line 8, in __init__
    self.refreshToken = oauth_response['refresh_token']
                        ~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
KeyError: 'refresh_token

But no idea how to fix it

**Comment by AfonsoFGarcia** [comment]
Well I have some good news!

Release 0.4.0 reworked the auth storage and it should be almost working now. I've reconfigured mine from scratch and it worked well, with the exception that now the notification receiver is broken somehow. But the integration should give you at least the option to unlock the door now.

Please try this release and let me know if it also worked out for you.

**Comment by swas** [comment]
Thanks a lot Alfonso!

It's working!!

**Comment by hugo1906** [comment]
Thanks

Enviado do meu iPhone

No dia 12/09/2024, às 21:32, swas ***@***.***> escreveu:

﻿

Thanks a lot Alfonso!

It's working!!

**Comment by AfonsoFGarcia** [comment]
Woohoo! This should allow you guys to control the lock. Unfortunately, the notifications for when someone rings it are broken as of now as the APIs from Google Firebase that were being used to receive the push notifications were deprecated and sundowned in the meanwhile. I don't know if or when I'm going to be able to get it back up.

Closing this issue as the integration itself is now working and the rest is going to have to be done on the library.

**Comment by pchaves1** [comment]
Thanks a lot Alfonso!

Since this is the only integration for Fermax, I hope you will have time to continue the great work in the future. :)

Best regards

**Comment by AfonsoFGarcia** [comment]
Seems like it's good news week for everybody! IF Fermax did not change anything on their API, this integration should be getting again the ring notifications as I found a replacement of the lib used to connect with Firebase that supports the new API for FCM and it's getting the notifications again.

If it's working as well for you guys, when starting up with version 0.5.0 you should get a notification on your smartphones that a new Android device has logged in. This is the integration :)

**Comment by pchaves1** [comment]
Great job!!

Thanks a lot Alfonso

**Comment by hugo1906** [comment]
Great job!!

Thanks a lot Alfonso


Enviado do meu iPhone

No dia 13/09/2024, às 10:43, pchaves1 ***@***.***> escreveu:

﻿

Great job!!

Thanks a lot Alfonso

**Comment by swas** [comment]
> Seems like it's good news week for everybody! IF Fermax did not change anything on their API, this integration should be getting again the ring notifications as I found a replacement of the lib used to connect with Firebase that supports the new API for FCM and it's getting the notifications again.
> 
> If it's working as well for you guys, when starting up with version 0.5.0 you should get a notification on your smartphones that a new Android device has logged in. This is the integration :)

Hello @AfonsoFGarcia

I'm ussing 0.5.1 and 0.6.1 versions 
In none of both I can't get the ring notification working. 

On 0.5.1 I have the entity "Fermax call status", but always is on Disconnected status. 

On 0.6.1 this entity it's not avaliable. 

Please can you help me? 

Thanks a lot!

**Comment by AfonsoFGarcia** [comment]
> Hello @AfonsoFGarcia
> 
> 
> 
> I'm ussing 0.5.1 and 0.6.1 versions 
> 
> In none of both I can't get the ring notification working. 
> 
> 
> 
> On 0.5.1 I have the entity "Fermax call status", but always is on Disconnected status. 
> 
> 
> 
> On 0.6.1 this entity it's not avaliable. 
> 
> 
> 
> Please can you help me? 
> 
> 
> 
> Thanks a lot! 

I think I was a bit too optimistic regarding the ring notifications. I had them working with the library but for some reason it wasn't working with Home Assistant, even though nothing changed on the library API.

Still need to figure out why it's not working with the integration.

Regarding 0.6.x releases not having the entity, the newest versions changed from using the old XMP based API from Google for push notifications (it was deprecated and sundown) to the newest API. This requires the API keys from Fermax for Firebase to work, which were the ones that they requested me to not share on the repo. In the latest minor version instead of showing a broken entity the integration will not add the entity if the notification system is not working.

**Comment by swas** [comment]
Thanks a lot @AfonsoFGarcia for the detailed explanation.

We will waiting for your magic 😁

Greetings

**Comment by hugo1906** [comment]
Don’t work in any version of software
Enviado do meu iPhone

No dia 29/09/2024, às 16:23, swas ***@***.***> escreveu:

﻿

Thanks a lot @AfonsoFGarcia<https://github.com/AfonsoFGarcia> for the detailed explanation.

We will waiting for your magic 😁

Greetings

**Comment by hugo1906** [comment]
O fluxo de configuração não pôde ser carregado: 500 Internal Server Error Server got itself in trouble

**Comment by hugo1906** [comment]
still don't work
